# Generated by Django 3.1.5 on 2021-01-11 12:39

import articleapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=articleapp.models.get_file_path),
        ),
    ]
